### ISSUE TITLE
Cache credentials does not work time to time

### ISSUE THREAD

**Issue by avs5** [Smartling/aws-profile#1]
Time to time got "None" as cached credentials, delete cache file helps. Have to investigate

**Comment by avs5** [comment]
bad format of session_token in file - it generate exception by read cached data - sesion_token looks like "FQoD.........ZCiyut29BQ=="}jwsc29BQ=="

**Comment by opokhvalit** [comment]
creds do not cached for me - script is asking token every time when I run terraform. Is that normal?

**Comment by avs5** [comment]
fixed with current release. Added truncate file after write to avoid additional BQ=="}jwsc29BQ=="
